// Demo data for the PIGE IMMO CRM application
// This provides realistic French real estate data for the UI

export const demoUser = {
  _id: 'demo-user-1',
  name: 'Marc Dupont',
  email: 'marc.dupont@iad-france.fr',
  role: 'agent',
  phone: '06 12 34 56 78',
  subscription: { plan: 'pro', status: 'active' },
  location: { city: 'Lyon', department: 'Rhône', region: 'Auvergne-Rhône-Alpes' },
  aiConfig: { canSuggestAppointments: false, autoRespond: false, tone: 'professional' },
  referralCode: 'MARC2024',
};

export const demoKPIs = {
  prospectsCount: 1247,
  prospectsChange: '+23 aujourd\'hui',
  callsToDo: 38,
  callsUrgent: '12 urgents',
  appointmentsPlanned: 7,
  appointmentsNote: '3 cette semaine',
  mandatesSigned: 4,
  mandatesNote: '+1 ce mois',
  voicemailsLeft: 23,
  voicemailsNote: '+5 aujourd\'hui',
};

export const demoPlatforms = [
  {
    name: 'Leboncoin',
    shortName: 'LBC',
    icon: '🏷️',
    active: true,
    total: 8432,
    todayNew: 127,
    weekTotal: 843,
    color: 'lbc',
  },
  {
    name: 'PAP',
    shortName: 'PAP',
    icon: '🔑',
    active: true,
    total: 3201,
    todayNew: 54,
    weekTotal: 312,
    color: 'pap',
  },
  {
    name: 'SeLoger',
    shortName: 'SLG',
    icon: '🏠',
    active: true,
    total: 5124,
    todayNew: 89,
    weekTotal: 621,
    color: 'seloger',
  },
  {
    name: 'Paru Vendu',
    shortName: 'PV',
    icon: '📰',
    active: false,
    total: 1823,
    todayNew: 31,
    weekTotal: 198,
    color: 'paruvendu',
  },
  {
    name: "Bien'ici",
    shortName: 'BI',
    icon: '🗺️',
    active: true,
    total: 4067,
    todayNew: 72,
    weekTotal: 412,
    color: 'bienici',
  },
];

export const demoProperties = [
  {
    _id: 'prop-1',
    title: 'Maison de charme 120m² avec jardin arboré',
    type: 'Maison',
    surface: 120,
    rooms: 5,
    bedrooms: 4,
    bathrooms: 2,
    price: 450000,
    priceHistory: [
      { price: 450000, date: '2026-03-01', change: 0 },
      { price: 460000, date: '2026-02-10', change: -2.2 },
      { price: 481000, date: '2026-01-20', change: -4.4 },
    ],
    location: { city: 'Lyon 3ème', address: 'Rue Garibaldi - Proche Part-Dieu' },
    source: 'leboncoin',
    images: ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800'],
    owner: { name: 'Jean-Marc Leblanc', phone: '06 12 34 56 78' },
    pricePerSqm: 3750,
    sectorAvgPricePerSqm: 4882,
    timeAgo: '2 min',
    isNew: true,
    description: 'Magnifique maison de 120m² avec jardin arboré de 250m², garage double, 4 chambres, salon lumineux avec cheminée. Cuisine équipée ouverte. DPE: C.',
    features: ['Cheminée', 'Double vitrage', 'Jardin'],
    energyClass: 'C',
    gesClass: 'D',
    yearBuilt: 1985,
    condition: 'Bon état',
    exposure: 'Sud-Ouest',
    saleType: 'Ancien',
    heating: 'Individuel',
    heatingMode: 'Gaz',
    annualEnergyCost: { min: 1200, max: 1800 },
    propertyTax: 1850,
    similarSales: [
      { address: 'Rue Garibaldi', price: 415000, pricePerSqm: 5026, date: 'Fév. 2026' },
      { address: 'Avenue Jean Jaurès', price: 402300, pricePerSqm: 4825, date: 'Jan. 2026' },
      { address: 'Allée des Platanes', price: 401975, pricePerSqm: 4931, date: 'Déc. 2025' },
    ],
    score: 96,
    phoneAvailable: true,
  },
  {
    _id: 'prop-2',
    title: 'Appartement T3 Haussmannien traversant',
    type: 'Appartement',
    surface: 65,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    price: 520000,
    location: { city: 'Paris 11ème', address: 'Rue Oberkampf - Métro Parmentier' },
    source: 'pap',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800'],
    owner: { name: 'Marie Duval', phone: '06 98 76 54 32' },
    pricePerSqm: 8000,
    sectorAvgPricePerSqm: 9200,
    timeAgo: '8 min',
    isNew: true,
    score: 92,
    phoneAvailable: true,
  },
  {
    _id: 'prop-3',
    title: 'Villa contemporaine avec piscine et vue dégagée',
    type: 'Maison',
    surface: 200,
    rooms: 7,
    bedrooms: 5,
    bathrooms: 3,
    price: 890000,
    location: { city: 'Aix-en-Provence', address: 'Chemin des Collines' },
    source: 'leboncoin',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800'],
    owner: { name: 'Philippe Martin', phone: '06 45 67 89 01' },
    pricePerSqm: 4450,
    sectorAvgPricePerSqm: 5200,
    timeAgo: '15 min',
    isNew: false,
    score: 88,
    phoneAvailable: true,
  },
  {
    _id: 'prop-4',
    title: 'T2 rénové avec balcon centre-ville',
    type: 'Appartement',
    surface: 42,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    price: 245000,
    location: { city: 'Bordeaux', address: 'Place des Quinconces' },
    source: 'leboncoin',
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800'],
    owner: { name: 'Sophie Bernard', phone: '06 23 45 67 89' },
    pricePerSqm: 5833,
    sectorAvgPricePerSqm: 4500,
    timeAgo: '22 min',
    isNew: false,
    score: 82,
    phoneAvailable: false,
  },
  {
    _id: 'prop-5',
    title: 'Maison de ville 150m² avec patio',
    type: 'Maison',
    surface: 150,
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    price: 389000,
    location: { city: 'Nantes', address: 'Rue de la Fosse' },
    source: 'pap',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800'],
    owner: { name: 'Antoine Rousseau', phone: '06 34 56 78 90' },
    pricePerSqm: 2593,
    sectorAvgPricePerSqm: 3100,
    timeAgo: '25 min',
    isNew: false,
    score: 85,
    phoneAvailable: true,
  },
  {
    _id: 'prop-6',
    title: 'T4 dernier étage avec vaste terrasse 85m²',
    type: 'Appartement',
    surface: 85,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 1,
    price: 310000,
    location: { city: 'Marseille 8ème', address: 'Avenue du Prado' },
    source: 'seloger',
    images: ['https://images.unsplash.com/photo-1493246507139-91e8bef99c02?auto=format&fit=crop&q=80&w=800'],
    owner: { name: 'Isabelle Petit', phone: '06 56 78 90 12' },
    pricePerSqm: 3647,
    sectorAvgPricePerSqm: 3800,
    timeAgo: '32 min',
    isNew: false,
    score: 91,
    phoneAvailable: true,
  },
  {
    _id: 'prop-7',
    title: 'Plain-pied 95m² avec véranda et garage',
    type: 'Maison',
    surface: 95,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 1,
    price: 279000,
    location: { city: 'Toulouse', address: 'Chemin des Vignes' },
    source: 'paruvendu',
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800'],
    owner: { name: 'Claude Moreau', phone: '06 67 89 01 23' },
    pricePerSqm: 2937,
    sectorAvgPricePerSqm: 3200,
    timeAgo: '45 min',
    isNew: false,
    score: 79,
    phoneAvailable: true,
  },
  {
    _id: 'prop-8',
    title: 'Duplex inversé 110m² avec rooftop privatif',
    type: 'Appartement',
    surface: 110,
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    price: 425000,
    location: { city: 'Strasbourg', address: 'Quai des Bateliers' },
    source: 'bienici',
    images: ['https://images.unsplash.com/photo-1527030280862-64139fba04ca?auto=format&fit=crop&q=80&w=800'],
    owner: { name: 'Éric Lefebvre', phone: '06 78 90 12 34' },
    pricePerSqm: 3864,
    sectorAvgPricePerSqm: 3500,
    timeAgo: '1h',
    isNew: false,
    score: 87,
    phoneAvailable: true,
  },
];

export const demoRadarLeads = [
  {
    _id: 'radar-1',
    title: 'Maison 140m² jardin + piscine',
    location: 'Lyon 6ème',
    price: 620000,
    timeAgo: '1 min',
    score: 96,
    isNew: true,
    source: 'leboncoin',
  },
  {
    _id: 'radar-2',
    title: 'T4 85m² dernier étage terrasse',
    location: 'Paris 15ème',
    price: 780000,
    timeAgo: '2 min',
    score: 93,
    isNew: true,
    source: 'pap',
  },
  {
    _id: 'radar-3',
    title: 'Loft 110m² rénové parking',
    location: 'Bordeaux Centre',
    price: 410000,
    timeAgo: '3 min',
    score: 92,
    isNew: true,
    source: 'seloger',
  },
];

export const demoLeads = [
  {
    _id: 'lead-1',
    property: demoProperties[0],
    status: 'a_prospecter',
    temperature: 'warm',
    source: 'scraping',
    agentTag: null,
  },
  {
    _id: 'lead-2',
    property: { ...demoProperties[3], title: 'T2 rénové 42m²', price: 245000, location: { city: 'Bordeaux' } },
    status: 'message_auto_envoye',
    temperature: 'warm',
    source: 'scraping',
    agentTag: null,
  },
  {
    _id: 'lead-3',
    property: demoProperties[0],
    status: 'rappel_prevu',
    temperature: 'hot',
    source: 'live_radar',
    callbackAt: 'Rappel 10h',
    agentTag: null,
  },
  {
    _id: 'lead-4',
    property: demoProperties[1],
    status: 'rdv_prevu',
    temperature: 'hot',
    source: 'scraping',
    appointmentAt: 'RDV demain 10h',
    agentTag: null,
  },
  {
    _id: 'lead-5',
    property: { ...demoProperties[5], title: 'T4 terrasse 85m²', price: 310000, location: { city: 'Marseille' } },
    status: 'rdv_prevu',
    temperature: 'hot',
    source: 'scraping',
    appointmentAt: null,
    agentTag: null,
  },
  {
    _id: 'lead-6',
    property: demoProperties[7],
    status: 'en_negociation',
    temperature: 'hot',
    source: 'scraping',
    notes: 'Offre en cours',
    agentTag: null,
  },
  {
    _id: 'lead-7',
    property: { ...demoProperties[4], title: 'Loft 180m²', price: 780000, location: { city: 'Lyon' } },
    status: 'mandat_signe',
    temperature: 'hot',
    source: 'scraping',
    agentTag: null,
  },
];

export const demoConversations = [
  {
    _id: 'conv-1',
    contactName: 'Jean-Marc Leblanc',
    channel: 'sms',
    status: 'active',
    unreadCount: 2,
    lastMessageAt: new Date(Date.now() - 5 * 60000),
    messages: [
      { sender: 'agent', content: 'Bonjour M. Leblanc, je suis Marc Dupont, conseiller IAD France. J\'ai vu votre maison à Lyon 3ème...', timestamp: new Date(Date.now() - 30 * 60000) },
      { sender: 'contact', content: 'Bonjour, oui la maison est toujours en vente. Vous souhaitez la visiter ?', timestamp: new Date(Date.now() - 20 * 60000) },
      { sender: 'agent', content: 'Absolument ! Quelles seraient vos disponibilités cette semaine ?', timestamp: new Date(Date.now() - 15 * 60000) },
      { sender: 'contact', content: 'Je suis disponible mercredi à 14h ou vendredi matin.', timestamp: new Date(Date.now() - 5 * 60000) },
    ],
  },
  {
    _id: 'conv-2',
    contactName: 'Marie Duval',
    channel: 'whatsapp',
    status: 'ai_managed',
    unreadCount: 0,
    lastMessageAt: new Date(Date.now() - 2 * 3600000),
    messages: [
      { sender: 'ai', content: 'Bonjour Mme Duval, je vous contacte au sujet de votre appartement T3 à Paris 11ème...', timestamp: new Date(Date.now() - 3 * 3600000), aiGenerated: true },
      { sender: 'contact', content: 'Je ne suis pas intéressée par une agence, merci.', timestamp: new Date(Date.now() - 2 * 3600000) },
    ],
  },
  {
    _id: 'conv-3',
    contactName: 'Philippe Martin',
    channel: 'platform',
    status: 'active',
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 45 * 60000),
    messages: [
      { sender: 'agent', content: 'Bonjour, votre villa à Aix-en-Provence m\'intéresse pour un de mes clients.', timestamp: new Date(Date.now() - 2 * 3600000) },
      { sender: 'contact', content: 'Avez-vous un client avec un budget de 850 000 à 900 000€ ?', timestamp: new Date(Date.now() - 45 * 60000) },
    ],
  },
  {
    _id: 'conv-4',
    contactName: 'Sophie Bernard',
    channel: 'sms',
    status: 'active',
    unreadCount: 0,
    lastMessageAt: new Date(Date.now() - 24 * 3600000),
    messages: [
      { sender: 'agent', content: 'Bonjour Mme Bernard, suite à notre échange...', timestamp: new Date(Date.now() - 24 * 3600000) },
    ],
  },
];

export const demoAppointments = [
  {
    _id: 'apt-1',
    title: 'Visite Maison Lyon 3ème',
    contactName: 'Jean-Marc Leblanc',
    location: 'Rue Garibaldi, Lyon 3ème',
    startTime: new Date(Date.now() + 2 * 86400000),
    endTime: new Date(Date.now() + 2 * 86400000 + 3600000),
    status: 'scheduled',
    contactPhone: '06 12 34 56 78',
  },
  {
    _id: 'apt-2',
    title: 'Signature Mandat Strasbourg',
    contactName: 'Éric Lefebvre',
    location: 'Quai des Bateliers, Strasbourg',
    startTime: new Date(Date.now() + 5 * 86400000),
    endTime: new Date(Date.now() + 5 * 86400000 + 3600000),
    status: 'scheduled',
    contactPhone: '06 78 90 12 34',
  },
];

export const kanbanColumns = [
  { id: 'a_prospecter', title: 'À prospecter', color: '#FF5722', dot: '#FF5722' },
  { id: 'message_auto_envoye', title: 'Message auto envoyé', color: '#F59E0B', dot: '#F59E0B' },
  { id: 'pas_de_reponse', title: 'Pas de réponse', color: '#EF4444', dot: '#EF4444' },
  { id: 'rappel_prevu', title: 'Rappel prévu', color: '#8B5CF6', dot: '#8B5CF6' },
  { id: 'non_interesse', title: 'Non intéressé', color: '#6B7280', dot: '#6B7280' },
  { id: 'rdv_prevu', title: 'RDV prévu', color: '#3B82F6', dot: '#3B82F6' },
  { id: 'no_show', title: 'No-show', color: '#EF4444', dot: '#EF4444' },
  { id: 'offre_envoyee', title: 'Offre envoyée', color: '#10B981', dot: '#10B981' },
  { id: 'en_negociation', title: 'En négociation', color: '#F59E0B', dot: '#F59E0B' },
  { id: 'mandat_signe', title: 'Mandat signé', color: '#10B981', dot: '#10B981' },
  { id: 'pas_de_suite', title: 'Pas de suite', color: '#6B7280', dot: '#6B7280' },
  { id: 'exclu', title: 'Exclu', color: '#EF4444', dot: '#EF4444' },
  { id: 'vendu', title: 'Vendu', color: '#10B981', dot: '#10B981' },
];

export const statusLabels = {
  a_prospecter: 'À prospecter',
  message_auto_envoye: 'Message auto envoyé',
  pas_de_reponse: 'Pas de réponse',
  rappel_prevu: 'Rappel prévu',
  non_interesse: 'Non intéressé',
  rdv_prevu: 'RDV prévu',
  no_show: 'No-show',
  offre_envoyee: 'Offre envoyée',
  en_negociation: 'En négociation',
  mandat_signe: 'Mandat signé',
  pas_de_suite: 'Pas de suite',
  exclu: 'Exclu',
  vendu: 'Vendu',
};
